# Site settings
title: ProjectMosul
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://projectmosul.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
